### ISSUE TITLE
syntax error with dev:template-vars

### ISSUE THREAD

**Issue by robfico** [peterjaap/magerun-addons#18]
Previous version returned blocks/var that needed to be whitelisted. Latest version, when run, shows:
___
$ n98-magerun.phar dev:template-vars
  [Zend_Db_Statement_Exception]                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty, query was:   
  [PDOException]                                                           
  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  
dev:template-vars [--addblocks[="..."]] [--addvariables[="..."]]
____

**Comment by hostep** [comment]
Fixed in PR #19
