### ISSUE TITLE
Add support for other than default SSH Ports

### ISSUE THREAD

**Issue by ottonet** [peterjaap/magerun-addons#2]
I run SSH on other then default Port. I assume others are doing this as well. You might want to add support for this. 

I changed line 65 of SyncCommand.php as follows: 

    $exec = 'rsync -avz -e "ssh -p ' . $values['port'] . '" --ignore-existing --exclude=*cache* ' . $values['username'] . '@' . $values['host'] . ':' . $values['path'] . DS . 'media ' . $this->getApplication()->getMagentoRootFolder();

And added <port>xxxx</port> to my local.xml. Works great. But to be portable it needs support for a default value as well.

**Comment by peterjaap** [comment]
Included! Thanks!

https://github.com/peterjaap/magerun-addons/commit/05161b80315857cc046672a05ee5a28332c25e46
