### ISSUE TITLE
pcntl_signal not defined

### ISSUE THREAD

**Issue by hans2103** [peterjaap/magerun-addons#21]
```
# n98-magerun dev:events:listen
Fatal error: Call to undefined function Elgentos\Magento\Command\Dev\Events\pcntl_signal() in /home/web/.n98-magerun/modules/magerun-addons/src/Elgentos/Magento/Command/Dev/Events/ListenCommand.php on line 33
```

Blijkbaar is deze functie niet geinstalleerd op deze server. 
Kan er ook omheen gewerkt worden door jouw addon? Of moet ik er bij de provider aandringen dat deze functie er bij komt?

**Comment by peterjaap** [comment]
Je kan er op aandringen om hem te installeren. Hij is technisch gezien niet nodig, zolang je maar handmatig de app/Mage.php.rej verwijdert en de revert-patch weer toepast (of app/Mage.php uit git uitcheckt).

**Comment by peterjaap** [comment]
Deze functie luistert namelijk gewoon naar CTRL-C en doet dan wat opruim werk.

**Comment by peterjaap** [comment]
Added a notice when pctnl_signal() doesn't exist; https://github.com/peterjaap/magerun-addons/commit/04601d988e70416fffe33ce740e13aa045e540c9

**Comment by tkn98** [comment]
@peterjaap: Just an idea: you might want to register a shutdown function that also reverts up the on-demand-patching (make sure it has the absolute path to the file). https://secure.php.net/register_shutdown_function

**Comment by peterjaap** [comment]
@tkn98 I've added it, just as an extra measure, but I don't really see the use case? It isn't fired when the script is killed by an external source.

**Comment by tkn98** [comment]
It's not a perfect safety-net but I thought it might help a bit. For example in case of an unforseen fatal error for example. If you offer a repair command that is able to restore and can be executed on it's own might be helpful as well in error situations like the reported one. But I have not idea on how to make this 100% fail-safe.

**Comment by hostep** [comment]
You could make it a toggle, like the `dev:template-hints` command. Run it once, it switches on, run it a second time, it switches off. Maybe that's an idea? The 'problem' with this is that you have to figure out what the current state is.
