### ISSUE TITLE
sh: 1: n98-magerun.phar: not found Tailing events...

### ISSUE THREAD

**Issue by tschifftner** [peterjaap/magerun-addons#28]
Unfortunately dev:events:listen does not work when having a global n98-magerun file (/usr/local/bin/n98-magerun).
```
sh: 1: n98-magerun.phar: not found
Tailing events...
```

**Comment by peterjaap** [comment]
Quick fix; ```alias n98-magerun.phar=n98-magerun```

I'll fix it later :)

**Comment by tschifftner** [comment]
nice :) Thank you.
