### ISSUE TITLE
Add 'Remove table prefix' command

### ISSUE THREAD

**Issue by peterjaap** [peterjaap/magerun-addons#31]
Because why would anyone in his right mind use the table prefix?!

**Comment by peterjaap** [comment]
Funnily enough, @yireo did just this, BUT THE OTHER WAY AROUND!

![head, wall](https://38.media.tumblr.com/2d73ab654fa936f51700496d20ed47a7/tumblr_inline_mm8xa6yLsC1qz4rgp.gif)

https://www.yireo.com/tutorials/magento/magento-administration/648-renaming-the-magento-database-table-prefix

**Comment by yireo** [comment]
LOL - thanks. This should be part of a Magerun command. Will add it to my todo :)

**Comment by peterjaap** [comment]
I actually by now have changed my mind on table prefixes and consider them as best practice. The reasoning is that for the most part, the database abstraction takes care of the prefix so you won't have to think about it. The upside; when, despite your best efforts, you actually do have an SQL injection vulnerability, your table names aren't guessable.
