### ISSUE TITLE
dev:template-vars with `false` arg values ignored

### ISSUE THREAD

**Issue by wkw** [peterjaap/magerun-addons#34]
Thanks for the great addons. just found them!

Report refers to this version [9dc5af0](https://github.com/peterjaap/magerun-addons/tree/9dc5af0ad701a6302adedc69710273aecb3b6449)

First time I ran  `dev:template-vars` I supplied false values for the options

> `n98-magerun.phar dev:template-vars --addblocks=false --addvariables=false`

but it added the blocks and vars anyway.

Deleted a couple of them and started testing variations to confirm. In order to NOT auto-add the blocks/vars, I have to leave off the options args completely.

I think this line: [`if ($this->_input->getOption('addblocks')) {`](https://github.com/peterjaap/magerun-addons/blob/9dc5af0ad701a6302adedc69710273aecb3b6449/src/Elgentos/Magento/Command/Dev/TemplateVars.php#L101) and the corresponding one for `addvariables` is simply reporting if a value was supplied for the argument, and not distinguishing between the value being true/false.

If I weren't in **SUPEE-6788 hell** at the moment I'd work up a patch to submit. apologies.

**Comment by peterjaap** [comment]
This is fixed in one of the latest PR's.
