### ISSUE TITLE
magerun extension:translations He does not find the translation

### ISSUE THREAD

**Issue by chrom** [peterjaap/magerun-addons#4]
But If you look below, you will notice that there are translations...

======================================================================================================================================================================
Filename: app/code/core/Mage/Connect/Block/Adminhtml/Extension/Custom/Edit/Tab/Package.php:          
Package Info
                                                                                                                              Translation en_US: NOT FOUND
======================================================================================================================================================================
Filename: app/code/core/Mage/Connect/Block/Adminhtml/Extension/Custom/Edit/Tab/Grid.php:             
Folder
                                                                                                                              Translation en_US: NOT FOUND
======================================================================================================================================================================
Filename: app/code/core/Mage/Connect/Block/Adminhtml/Extension/Custom/Edit/Tab/Grid.php:             
Package
                                                                                                                              Translation en_US: NOT FOUND
======================================================================================================================================================================

Copy/paste this into app/locale/en_US/Mage_Connect.csv and add the translations;
"1.5.0.0 & later","1.5.0.0 & later"
"Add Author","Add Author"
"Add files","Add files"
"Authors","Authors"
"Channel","Channel"
"Contents","Contents"
"Create Extension Package","Create Extension Package"
"Dependencies","Dependencies"
"Description","Description"
"Edit Extension","Edit Extension"
"Failed to create the package.","Failed to create the package."
"Failed to load the package data.","Failed to load the package data."
"Failed to save the package.","Failed to save the package."
"Folder","Folder"
"License","License"
"License URI","License URI"
"Load Local Package","Load Local Package"
"Load local Package","Load local Package"
"Magento Connect","Magento Connect"
"Maximum","Maximum"
"Minimum","Minimum"
"Name","Name"
"New Extension","New Extension"
"Notes","Notes"
"PHP Version","PHP Version"
"Package","Package"
"Package Extensions","Package Extensions"
"Package File Name","Package File Name"
"Package Info","Package Info"
"Pre-1.5.0.0","Pre-1.5.0.0"
"Release","Release"
"Release Info","Release Info"
"Release Stability","Release Stability"
"Release Version","Release Version"
"Remove","Remove"
"Save As...","Save As..."
"Save Data and Create Package","Save Data and Create Package"
"Save package with custom package file name","Save package with custom package file name"
"Summary","Summary"
"Supported releases","Supported releases"
"System","System"
"The package %s data has been loaded.","The package %s data has been loaded."
"The package data has been saved.","The package data has been saved."
"There was a problem saving package data","There was a problem saving package data"

**Comment by peterjaap** [comment]
It's very hard to find all translations. This command is merely a helper.

**Comment by peterjaap** [comment]
Also see #1
