### ISSUE TITLE
Module uninstallation aid

### ISSUE THREAD

**Issue by szepeviktor** [peterjaap/magerun-addons#57]
As there is no way - outside web-based Magento Connect - to uninstall a module (mainly local ones) it would be nice to have some kind "half done automatically, half by notices" uninstall command.

**Comment by szepeviktor** [comment]
```
$ n98-magerun dev:module:uninstall
1. Please delete these files: ...
2. Please delete these tables: ...
3. And do this: ....
```

**Comment by peterjaap** [comment]
You could incorporate MEFF (https://github.com/tegansnyder/meff) to give a list of files that should be deleted. 

The hard part though is the database stuff; you'll have to read out the sql files and create antonyms for those queries.

**Comment by peterjaap** [comment]
Not sure though If I myself want to spend more time on this since we use composer for all our Magento 1 projects so with composer it's just a matter of `composer remove extension_name_here`. That leaves the database part of course.

**Comment by szepeviktor** [comment]
Thank you.
