### ISSUE TITLE
Does the remove orphans command take images into account that are assigned at the store scope?

### ISSUE THREAD

**Issue by tylerssn** [peterjaap/magerun-addons#61]

**Comment by peterjaap** [comment]
Yes it does not differentiate between images that are in the store or in any other scope. See https://github.com/peterjaap/magerun-addons/blob/90491d39f20b287a89ce0b40d14ded26a4b93bd1/src/Elgentos/Magento/Command/Media/Images/AbstractCommand.php#L144
and https://github.com/peterjaap/magerun-addons/blob/90491d39f20b287a89ce0b40d14ded26a4b93bd1/src/Elgentos/Magento/Command/Media/Images/AbstractCommand.php#L183
