### ISSUE TITLE
dev:template-vars output

### ISSUE THREAD

**Issue by robfico** [peterjaap/magerun-addons#7]
When running this check:
n98-magerun.phar dev:template-vars

we often find output like this (even on very vanilla installs):
____
Found blocks that are not whitelisted by default; 
cms/block

Found template/block variables that are not whitelisted by default; 
trans_email/ident_support/email
____

Is this expected, or do these need to be added to the whitelist once patched?

**Comment by erfanimani** [comment]
Not sure why it's saying that.. `trans_email/ident_support/email` seems to be whitelisted by default:

See `app/code/core/Mage/Admin/sql/admin_setup/upgrade-1.6.1.1-1.6.1.2.php:57`

**Comment by peterjaap** [comment]
Just fixed this
